"""add related_post_id to notification

Revision ID: 0164f4f99e91
Revises: e074518b0a12
Create Date: 2025-12-21 14:13:23.095109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0164f4f99e91'
down_revision = 'e074518b0a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_post_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('related_post_id')

    # ### end Alembic commands ###
