"""Add user settings fields

Revision ID: 0ebdfc6aacf6
Revises: 8fd0353e7442
Create Date: 2025-12-21 13:24:48.823702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ebdfc6aacf6'
down_revision = '8fd0353e7442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_profile_public', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('show_email', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('notify_new_message', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('notify_comment_reply', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('notify_post_like', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('receive_email_notifications', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('receive_email_notifications')
        batch_op.drop_column('notify_post_like')
        batch_op.drop_column('notify_comment_reply')
        batch_op.drop_column('notify_new_message')
        batch_op.drop_column('show_email')
        batch_op.drop_column('is_profile_public')

    # ### end Alembic commands ###