"""empty message

Revision ID: 152c386614e1
Revises: d034fb5779a3
Create Date: 2025-12-21 09:02:53.624794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152c386614e1'
down_revision = 'd034fb5779a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_table('like',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('create_time', sa.DateTime(), nullable=True),
        sa.Column('user_id', sa.String(length=100), nullable=False),
        sa.Column('post_id', sa.Integer(), nullable=True),
        sa.Column('comment_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
        sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'comment_id', name='_user_comment_like_uc'),
        sa.UniqueConstraint('user_id', 'post_id', name='_user_post_like_uc')
        )
    except Exception as e:
        # 如果表已经存在，跳过创建操作
        print(f"跳过 'like' 表创建: {e}")
    
    try:
        op.create_table('report',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('reason', sa.Text(), nullable=False),
        sa.Column('create_time', sa.DateTime(), nullable=True),
        sa.Column('is_handled', sa.Boolean(), nullable=True),
        sa.Column('user_id', sa.String(length=100), nullable=False),
        sa.Column('post_id', sa.Integer(), nullable=True),
        sa.Column('comment_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
        sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    except Exception as e:
        # 如果表已经存在，跳过创建操作
        print(f"跳过 'report' 表创建: {e}")
    
    try:
        with op.batch_alter_table('comment', schema=None) as batch_op:
            batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key(None, 'comment', ['parent_id'], ['id'])
    except Exception as e:
        # 如果已经执行过该操作，跳过
        print(f"跳过 comment 表更新: {e}")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_id')

    op.drop_table('report')
    op.drop_table('like')
    # ### end Alembic commands ###