"""add notify_comment_like field to user

Revision ID: 85b5490295e3
Revises: 0164f4f99e91
Create Date: 2025-12-21 14:21:55.718972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b5490295e3'
down_revision = '0164f4f99e91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_comment_like', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notify_comment_like')

    # ### end Alembic commands ###
