"""add notification model

Revision ID: e074518b0a12
Revises: 0ebdfc6aacf6
Create Date: 2025-12-21 14:00:00.151337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e074518b0a12'
down_revision = '0ebdfc6aacf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('sender_id', sa.String(length=100), nullable=True),
    sa.Column('type', sa.Enum('NEW_MESSAGE', 'COMMENT_REPLY', 'POST_LIKE', 'COMMENT_LIKE', 'POST_COMMENT', 'SYSTEM_NOTICE', name='notificationtype'), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('related_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # ### end Alembic commands ###